apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-volume
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard



